matrix:
  include:
    - language: python
      python: 2.7
      before_script:
        - cd python
      script:
        - python -m unittest discover -p Test.py

    - language: python
      python: 3.6
      before_script:
        - cd python
      script:
        - python -m unittest discover -p Test.py

    - language: python
      python: nightly
      before_script:
        - cd python
      script:
        - python -m unittest discover -p Test.py

    - language: go
      go: master
      before_script:
        - cd go
      install:
        - go get github.com/hyperledger/fabric/core/chaincode/shim
      script:
        - pwd
        - ls -al
        - go build ./

notifications:
  email:
    - test@23-5.eu

