matrix:
  include:
    - language: python
      python: 2.7
      before_script:
        - cd python
      script:
        - python -m unittest discover -p Test.py

    - language: python
      python: 3.6
      before_script:
        - cd python
      script:
        - python -m unittest discover -p Test.py

    - language: python
      python: nightly
      before_script:
        - cd python
      script:
        - python -m unittest discover -p Test.py

    - language: go
      before_script:
        - cd go
      go: release
      install:
       - go get github.com/hyperledger/fabric/core/chaincode/shim
      script:
        - go test -v ./...

notifications:
  email:
    - test@23-5.eu

