matrix:
  include:
    - language: python
      python: 2.7
      python: 3.6
      before_script:
        - cd python
      script:
        - python -m unittest discover -p Test.py

   # - language: go
   #   before_script:
   #     - cd go
   #   go:
   #    - master
   #   script:
   #     - ./gradlew build connectedCheck

notifications:
  email:
    - test@23-5.eu

