matrix:
  include:
    - language: python
      python: 2.7
      before_script:
        - cd python
      script:
        - python -m unittest discover -p Test.py

    - language: python
      python: nightly
      before_script:
        - cd python
      script:
        - python -m unittest discover -p Test.py

    - language: node_js
      node_js: 7
      before_script:
        - cd javascript
      script:
        - ls

    - language: go
      go: master
      before_script:
        - cd go
      install:
        - mkdir -p $GOPATH/src/github.com/hyperledger
        - git   -C $GOPATH/src/github.com/hyperledger clone -b v0.6 http://gerrit.hyperledger.org/r/fabric
      script:
        - go build ./

notifications:
  email:
    - test@23-5.eu

